apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-game-nginx
  labels:
    app: number-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-game
  template:
    metadata:
      labels:
        app: number-game
    spec:
      containers:
      - name: nginx
        image: dockerakilesh/number-game:latest
 # Add this line
        ports:
        - containerPort: 80