groups:
  - name: number-game-alerts
    interval: 30s
    rules:
      # Alerts for all teams
      - alert: ServiceDown
        expr: up{job="number-game"} == 0
        for: 1m
        labels:
          severity: critical
          team: sre
          audience: all
        annotations:
          summary: "Number Game service is down"
          description: "Service has been down for more than 1 minute"
          
      # Development team alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          team: development
          audience: developers
        annotations:
          summary: "High response time detected"
          description: "P95 response time is {{ $value }}s"
          
      # SRE team alerts
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{pod=~"number-game.*"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          team: sre
          audience: operations
        annotations:
          summary: "High CPU usage on pod"
          description: "Pod {{ $labels.pod }} CPU usage is {{ $value }}%"
          
      # Management alerts
      - alert: LowUserEngagement
        expr: increase(games_started_total[1h]) < 5
        for: 30m
        labels:
          severity: info
          team: management
          audience: business
        annotations:
          summary: "Low user engagement detected"
          description: "Only {{ $value }} games started in the last hour"
          
      # Security team alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          team: security
          audience: security
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }}"